### ISSUE TITLE
关于模拟假条

### ISSUE THREAD

**Issue by kimoefox** [uiolee/NanFuDao#7]
首先先感谢作者大大提供这么丰富的功能，每天打卡方便多了

####情况####
假条模拟当中，我已经同时再rewrite里面添加了您的两个JS
因此，在进入页面时，请假列表上面有休假中的褐色提示
然而，点击进去查看，里面的内容上面却显示已结束

####背景####
我的请假从新到旧，在【正常请假】的那一次的更新一次有个【已撤回】的情况，是否与这个有关？

####猜测####
是不是【已撤回】的提示在什么原因下会“盖住“【已通过】？

**Comment by uiolee** [comment]
首先我这里测试一切正常，没有出现你所说的状况。

对于你说的假条详情页中显示已结束，请你查看日志，确认detail.js脚本是否有运行。

对于你说的`已撤回`，我未能理解是你请假时进行了撤回，还是脚本导致它变成了撤回。如果是你手动撤回，并不会影响脚本运行。

**Comment by kimoefox** [comment]
感谢大佬的解答🙏
根据你的指导，我去翻了一下日志，看到确实没有调用detail.js，原因是我把类型选错了。。。

给大佬带来不便还请见谅QAQ
