### ISSUE TITLE
希望能模拟出校二维码

### ISSUE THREAD

**Issue by zhang8878** [uiolee/NanFuDao#9]
模拟假条有效，但是，我的—出入校二维码显示的是灰色，希望更新一下(我们学校只看请假
![728FEDE1-3025-41E6-B0D2-0AE63BBBDEA7](https://user-images.githubusercontent.com/113912846/191028354-654ca0c0-efcd-48ba-8050-e9ce0895014c.jpeg)
二维码是否为绿色，因为有实时时间，不用扫描）

**Comment by Zyh1297171015** [comment]
把red改为green就行

**Comment by zhang8878** [comment]
不是懒狗，我是小白研究了好久勉强抓到了包但是不会改，大佬能否给个js脚本

**Comment by zhang8878** [comment]
> 模拟假条有效，但是，我的—出入校二维码显示的是灰色，希望更新一下(我们学校只看请假
> ![728FEDE1-3025-41E6-B0D2-0AE63BBBDEA7](https://user-images.githubusercontent.com/113912846/191028354-654ca0c0-efcd-48ba-8050-e9ce0895014c.jpeg)
> 二维码是否为绿色，因为有实时时间，不用扫描）
